### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNativeMatrixSdk.default.configure')

### ISSUE THREAD

**Issue by NeerajPise** [hannojg/react-native-matrix-sdk#19]
I'm on react-native-matrix-sdk@1.0.0-alpha74. After installing it using the mentioned steps, I ran into the error on the first code line after importing (MatrixSdk.configure('http://localhost:8008')) - 
```
TypeError: null is not an object (evaluating '_reactNativeMatrixSdk.default.configure')

This error is located at:
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in DevAppContainer (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
```
Do you know what could cause this?

P.S. While installing, I got the following error so I installed with the --legacy-peer-deps flag
<img width="669" alt="Screenshot 2021-12-17 at 11 25 43 AM" src="https://user-images.githubusercontent.com/44890047/146498642-cc6fbf58-63ee-40cf-bbed-abc25b0691a2.png">

**Comment by vunguyen464301** [comment]
i faced this problem, so i didn't have any solution !
